# coding: utf-8

"""
    Yagna Activity API

    It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_activity_client
from openapi_activity_client.api.requestor_state_api import RequestorStateApi  # noqa: E501
from openapi_activity_client.rest import ApiException


class TestRequestorStateApi(unittest.TestCase):
    """RequestorStateApi unit test stubs"""

    def setUp(self):
        self.api = openapi_activity_client.api.requestor_state_api.RequestorStateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_activity_state(self):
        """Test case for get_activity_state

        Get state of specified Activity.  # noqa: E501
        """
        pass

    def test_get_activity_usage(self):
        """Test case for get_activity_usage

        Get usage of specified Activity.  # noqa: E501
        """
        pass

    def test_get_running_command(self):
        """Test case for get_running_command

        Get running command for a specified Activity.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
