# coding: utf-8

"""
    Yagna Activity API

    It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_activity_client
from openapi_activity_client.api.provider_api import ProviderApi  # noqa: E501
from openapi_activity_client.rest import ApiException


class TestProviderApi(unittest.TestCase):
    """ProviderApi unit test stubs"""

    def setUp(self):
        self.api = openapi_activity_client.api.provider_api.ProviderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_collect_activity_events(self):
        """Test case for collect_activity_events

        Fetch Requestor command events.  # noqa: E501
        """
        pass

    def test_get_activity_state(self):
        """Test case for get_activity_state

        Get state of specified Activity.  # noqa: E501
        """
        pass

    def test_get_activity_usage(self):
        """Test case for get_activity_usage

        Get usage of specified Activity.  # noqa: E501
        """
        pass

    def test_set_activity_state(self):
        """Test case for set_activity_state

        Set state of specified Activity.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
