# coding: utf-8

"""
    Yagna Activity API

    It conforms with capability level 1 of the [Activity API specification](https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM).  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_activity_client
from openapi_activity_client.api.requestor_control_api import RequestorControlApi  # noqa: E501
from openapi_activity_client.rest import ApiException


class TestRequestorControlApi(unittest.TestCase):
    """RequestorControlApi unit test stubs"""

    def setUp(self):
        self.api = openapi_activity_client.api.requestor_control_api.RequestorControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call_exec(self):
        """Test case for call_exec

        Executes an ExeScript batch within a given Activity.  # noqa: E501
        """
        pass

    def test_create_activity(self):
        """Test case for create_activity

        Creates new Activity based on given Agreement.  # noqa: E501
        """
        pass

    def test_destroy_activity(self):
        """Test case for destroy_activity

        Destroys given Activity.  # noqa: E501
        """
        pass

    def test_get_exec_batch_results(self):
        """Test case for get_exec_batch_results

        Queries for ExeScript batch results.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
