version: "3.3"

services:
    router:
        image: yagna
        build:
            context: .
            dockerfile: yagna.Dockerfile
            args:
                GITHUB_API_TOKEN: $GITHUB_API_TOKEN
        entrypoint: /usr/bin/ya_sb_router
        command: ["-l", "tcp://0.0.0.0:7477"]

    mock-api:
        image: golemfactory/golem-client-mock:0.1.1
        ports:
            - "5001:5001"

    requestor:
        image: yagna
        entrypoint: /usr/bin/yagna
        command: ["service", "run", "-d", "/"]
        depends_on:
            - router
            - mock-api
        env_file:
            - .env
        ports:
            - "6000:6000"
            - "6010:6010"
        volumes:
            - "./asset:/asset"

    provider:
        image: yagna
        entrypoint: /usr/bin/yagna
        command: ["service", "run", "-d", "/"]
        depends_on:
            - router
            - mock-api
        env_file:
            - .env
        ports:
            - "6001:6000"
            - "6011:6010"
        environment:
            - EXE_UNIT_PATH=/asset/local-exeunits-descriptor.json
        volumes:
            - "./asset:/asset"
