version: "3.3"

services:

    router:
        image: yagna-goth
        build:
            context: .
            dockerfile: yagna-goth.Dockerfile
            args:
                GITHUB_API_TOKEN: $GITHUB_API_TOKEN
                YAGNA_BRANCH: ${YAGNA_BRANCH:-master}
                YAGNA_COMMIT_HASH: $YAGNA_COMMIT_HASH
        entrypoint: /usr/bin/ya_sb_router
        command: ["-l", "tcp://0.0.0.0:7477"]

    mock-api:
        image: golem-client-mock
        build:
            context: .
            dockerfile: mock-api.Dockerfile
        command: dotnet GolemClientMocksaAPI.dll --Logging:LogLevel:Default=Debug
        ports:
            - "5001:5001"

    proxy-nginx:
        # A service that runs `nginx` and routes API calls to
        # the `mitmproxy` instance running as part of the test
        # harness on the host machine
        image: proxy-nginx
        build:
            context: ../
            dockerfile: docker/proxy-nginx.Dockerfile

    ethereum:
        image: docker.pkg.github.com/golemfactory/gnt2/gnt2-docker-yagna:c4a1fb9cbcf3
        ports:
            - "8545:8545"

networks:
    default:
        ipam:
            config:
                # Fix the IP address range to ensure the host machine
                # is reachable at the fixed address 172.19.0.1
                - subnet: 172.19.0.0/16
