version: "3.3"

services:

    router:
        image: ${DOCKER_PKG}/yagna-goth:${YAGNA_DEB}
        build:
            context: .
            dockerfile: yagna-goth.Dockerfile
            args:
                GITHUB_API_TOKEN: $GITHUB_API_TOKEN
        entrypoint: /usr/bin/ya_sb_router
        command: ["-l", "tcp://0.0.0.0:7477"]     

    mock-api:
        image: golemfactory/golem-client-mock:0.1.2
        ports:
            - "5001:5001"
