version: "3.3"

services:

    router:
        image: yagna-goth
        entrypoint: /usr/bin/ya_sb_router
        command: ["-l", "tcp://0.0.0.0:7477"]

    mock-api:
        image: golem-client-mock
        build:
            context: .
            dockerfile: mock-api.Dockerfile
        command: dotnet GolemClientMocksaAPI.dll --Logging:LogLevel:Default=Debug
        ports:
            - "5001:5001"

    proxy-nginx:
        # A service that runs `nginx` and routes API calls to
        # the `mitmproxy` instance running as part of the test
        # harness on the host machine
        image: proxy-nginx

    ethereum:
        image: docker.pkg.github.com/golemfactory/gnt2/gnt2-docker-yagna:c4a1fb9cbcf3
        ports:
            - "8545:8545"

    zksync:
        image: docker.pkg.github.com/golemfactory/yagna-zksync/yagna-zksync-mock:a352987631ba
        ports:
            - "3030:3030"
        environment:
            - WEB3_PROVIDER_URI=http://ethereum:8545
        depends_on:
            - ethereum


networks:
    default:
        ipam:
            config:
                # Fix the IP address range to ensure the host machine
                # is reachable at the fixed address 172.19.0.1
                - subnet: 172.19.0.0/16
