# Note: values of keys denoting paths are resolved relative to the directory
# in which this file is located.
# The tokens `~` and `~user` are also replaced by the corresponding users's
# home directory.

docker-compose:

  docker-dir: "docker/"

  build-environment:
    # TODO:
    # For now these settings are common to all `yagna` containers.
    # In future we may want to have nodes running different versions
    # of `yagna` in the test network.

    # binary-path: ...
    # deb-path: ...
    # branch: ...
    # commit-hash: ...
    # release-tag: ...
    # use-prerelease: ...

  compose-log-patterns:
    ethereum: ".*Wallets supplied."
    zksync: ".*Running on http://.*:3030/.*"


key-dir: "keys"


web-root: "web-root"


node-types:
  # Each node type is a collection of attributes common to a group of nodes.
  # Required attributes are "name" and "class".

  - name: "Requestor"
    class: "goth.runner.probe.RequestorProbe"

  - name: "VM-Wasm-Provider"
    class: "goth.runner.probe.ProviderProbe"
    mount:
      - read-only: "provider/presets.json"
        destination: "/root/.local/share/ya-provider/presets.json"
      - read-only: "provider/hardware.json"
        destination: "/root/.local/share/ya-provider/hardware.json"
      - read-write: "~/.local/share/ya-provider/vm-images"
        destination: "/root/.local/share/ya-provider/exe-unit/cache"
    privileged-mode: True

nodes:

  - name: "requestor"
    type: "Requestor"
    use-proxy: True

  - name: "provider-1"
    type: "VM-Wasm-Provider"
    use-proxy: True

  - name: "provider-2"
    type: "VM-Wasm-Provider"
    use-proxy: True
