# coding: utf-8

"""
    Yagna Market API

     ## Yagna Market The Yagna Market is a core component of the Yagna Network, which enables computational Offers and Demands circulation. The Market is open for all entities willing to buy computations (Demands) or monetize computational resources (Offers). ## Yagna Market API The Yagna Market API is the entry to the Yagna Market through which Requestors and Providers can publish their Demands and Offers respectively, find matching counterparty, conduct negotiations and make an agreement.  This version of Market API conforms with capability level 1 of the <a href=\"https://docs.google.com/document/d/1Zny_vfgWV-hcsKS7P-Kdr3Fb0dwfl-6T_cYKVQ9mkNg\"> Market API specification</a>.  Market API contains two roles: Requestors and Providers which are symmetrical most of the time (excluding agreement phase).   # noqa: E501

    The version of the OpenAPI document: 1.5.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_market_client
from openapi_market_client.api.requestor_api import RequestorApi  # noqa: E501
from openapi_market_client.rest import ApiException


class TestRequestorApi(unittest.TestCase):
    """RequestorApi unit test stubs"""

    def setUp(self):
        self.api = openapi_market_client.api.requestor_api.RequestorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_agreement(self):
        """Test case for cancel_agreement

        Cancels agreement.  # noqa: E501
        """
        pass

    def test_collect_offers(self):
        """Test case for collect_offers

        Reads Market responses to published Demand.  # noqa: E501
        """
        pass

    def test_confirm_agreement(self):
        """Test case for confirm_agreement

        Sends Agreement draft to the Provider.  # noqa: E501
        """
        pass

    def test_counter_proposal_demand(self):
        """Test case for counter_proposal_demand

        Responds with a bespoke Demand to received Offer.  # noqa: E501
        """
        pass

    def test_create_agreement(self):
        """Test case for create_agreement

        Creates Agreement from selected Proposal.  # noqa: E501
        """
        pass

    def test_get_agreement(self):
        """Test case for get_agreement

        Fetches agreement with given agreement id.  # noqa: E501
        """
        pass

    def test_get_demands(self):
        """Test case for get_demands

        Fetches all active Demands which have been published by the Requestor.  # noqa: E501
        """
        pass

    def test_get_proposal_offer(self):
        """Test case for get_proposal_offer

        Fetches Proposal (Offer) with given id.  # noqa: E501
        """
        pass

    def test_post_query_reply_demands(self):
        """Test case for post_query_reply_demands

        Handles dynamic property query.  # noqa: E501
        """
        pass

    def test_reject_proposal_offer(self):
        """Test case for reject_proposal_offer

        Rejects Proposal (Offer).  # noqa: E501
        """
        pass

    def test_subscribe_demand(self):
        """Test case for subscribe_demand

        Publishes Requestor capabilities via Demand.  # noqa: E501
        """
        pass

    def test_terminate_agreement(self):
        """Test case for terminate_agreement

        Terminates approved Agreement.  # noqa: E501
        """
        pass

    def test_unsubscribe_demand(self):
        """Test case for unsubscribe_demand

        Stop subscription for previously published Demand.  # noqa: E501
        """
        pass

    def test_wait_for_approval(self):
        """Test case for wait_for_approval

        Waits for Agreement approval by the Provider.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
