name: Run codestyle
on:
  push:
jobs:
  build:
    name: Run black codestyle check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install developer requirements
        run: pip install -r requirements-dev.txt

      - name: Print installed package versions
        run: pip freeze

      - name: Run black codestyle in check mode
        run: black . --check
