name: codestyle

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:
  codestyle:
    name: Check code style
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and configure Poetry
        run: python -m pip install poetry==1.6.1

      - name: Install dependencies
        # TODO install dev dependencies only (https://github.com/python-poetry/poetry/issues/2572)
        run: poetry install --no-root

      - name: Run formatters in check mode
        run: poetry run poe checks_codestyle
