name: codestyle

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:
  codestyle:
    name: Check code style
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          poetry --version
        

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run formatters in check mode
        run: poetry run poe checks_codestyle
