name: codestyle

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:
  codestyle:
    name: Check code style
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4

      - name: Install dependencies
        # TODO install dev dependencies only (https://github.com/python-poetry/poetry/issues/2572)
        run: poetry install --no-root

      - name: Run black formatter in check mode
        run: poetry run poe codeformat
      
      - name: Run flake8 codestyle checker
        run: poetry run poe codestyle
