name: codestyle
on:
  push:
jobs:
  sort-requirements:
    name: sort requirements
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if requirements are sorted properly
        run: ls | grep '^requirements.*txt$' | LC_ALL=C xargs -I@ sort --ignore-case -c @

  codestyle:
    name: black flake8
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Print python and pip version
        run: python --version && pip --version

      - name: Install developer requirements
        run: pip install -r requirements-dev.txt

      - name: Print installed package versions
        run: pip freeze

      - name: Run black codestyle in check mode
        run: black . -v --check --diff

      - name: Run flake8 codestyle
        run: flake8
