name: integration-test

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:

  yagna-e2e:
    name: Run integration tests (yagna E2E)
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4

      - name: Install dependencies
        run: poetry install --no-root

      - name: Log in to GitHub Docker repository
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{github.actor}} --password-stdin

      - name: Run test suite
        env:
          ENABLE_VM_TESTS: 'true'
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run poe ci_test_self_hosted --yagna-release latest

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: goth-logs
          path: /tmp/goth-tests

      # Only relevant for self-hosted runners
      - name: Remove test logs
        if: always()
        run: rm -rf /tmp/goth-tests
