name: Integration tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration-test:
    name: Run integration tests
    runs-on: [goth-22.04]

    strategy:
      matrix:
        pyver: [ "3.10", "3.11", "3.12" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install gcc
        run: sudo apt-get install -y gcc g++ make

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1

      - name: Install dependencies
        run: poetry install

      # Only relevant for self-hosted runners
      - name: Cleanup Docker
        if: always()
        run: |
          c=$(docker ps -q) && [[ $c ]] && docker kill $c
          docker system prune -af

      - name: Log in to GitHub Docker repository
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Run integration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run poe tests_integration

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: goth-logs
          path: /tmp/goth-tests

      # Only relevant for self-hosted runners
      - name: Remove test logs
        if: always()
        run: rm -rf /tmp/goth-tests

      # Only relevant for self-hosted runners
      - name: Remove poetry virtual env
        if: always()
        run: poetry env remove --all

      # Only relevant for self-hosted runners
      - name: Cleanup Docker
        if: always()
        run: |
          c=$(docker ps -q) && [[ $c ]] && docker kill $c
          docker system prune -af