name: integration-test

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:

  yagna-e2e:
    name: Run integration tests (yagna E2E)
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Print python and pip version
        run: python --version && pip --version

      - name: Run setuptools
        run: python setup.py develop

      - name: Print installed package versions
        run: pip freeze

      - name: Log in to GitHub Docker repository
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{github.actor}} --password-stdin

      - name: Run test suite
        env:
          ENABLE_VM_TESTS: 'true'
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ugly hack to make assets work, fix progress tracked here: https://github.com/golemfactory/yagna-integration/issues/336
        run: python -m pytest test/yagna --assets-path=/opt/actions-runner/_work/yagna-integration/yagna-integration/test/yagna/e2e/assets -svx

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: goth-logs
          path: /tmp/goth-tests
