name: Integration tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration-test:
    name: Run integration tests
    runs-on: [ubuntu-22.04]

    strategy:
      matrix:
        pyver: [ "3.10", "3.11", "3.12" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install Poetry
        run: python3 .github/scripts/poetry_install.py --version 1.8.2

      - name: Install dependencies
        run: poetry install

      - name: Run integration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run poe tests_integration

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: ${{ matrix.pyver == '3.12' }}
        with:
          name: goth-logs
          path: /tmp/goth-tests