name: integration-test

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:

  yagna-e2e:
    name: Run integration tests (yagna E2E)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Print python and pip version
        run: python --version && pip --version

      - name: Run setuptools
        run: python setup.py develop

      - name: Print installed package versions
        run: pip freeze

      - name: Log in to GitHub Docker repository
        run: echo ${{ secrets.YAGNA_WORKFLOW_TOKEN }} | docker login docker.pkg.github.com -u ${{github.actor}} --password-stdin

      - name: Run test suite
        env:
          GITHUB_API_TOKEN: ${{ secrets.YAGNA_WORKFLOW_TOKEN }}
        run: python -m pytest test/yagna --assets-path=/home/runner/work/goth/goth/test/yagna/e2e/assets -svx --log-cli-level=DEBUG

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: goth-logs
          path: /tmp/goth-tests
