name: test

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:
  level0:
    name: Run integration tests (level 0)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the docker-compose stack
        env:
          GITHUB_API_TOKEN: ${{ secrets.YAGNA_WORKFLOW_TOKEN }}
        run: docker-compose -f docker/docker-compose.yml up -d

      - name: Configure python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Print python and pip version
        run: python --version && pip --version

      - name: Run setuptools
        run: python setup.py develop

      - name: Print installed package versions
        run: pip freeze

      - name: Sleep
        run: sleep 10

      - name: Check running containers
        run: docker ps

      - name: Run unit tests
        run: python -m pytest test/runner -svx

      - name: Run test suite
        run: python -m pytest test/level0 -svx --log-cli-level=DEBUG

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-logs
          path: /tmp/yagna-tests
