name: test

on:
  push:
    branches:
      - master
      - mwu/setup_req
  pull_request:
    branches:
      - master

jobs:
  level0:
    name: level0
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose -f src/docker/docker-compose.yml up -d

      - name: Configure python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Print python and pip version
        run: python --version && pip --version

      - name: Install developer requirements
        run: pip install -r requirements.txt

      - name: Run setuptools
        run: python setup.py develop

      - name: Print installed package versions
        run: pip freeze

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Check running containers
        run: docker ps

      - name: Run test suite
        run: python -m pytest test/level0 -svx --log_cli_level=DEBUG
