name: test

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:
  level0:
    name: level0
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare assets for level0
        run: mkdir -p src/docker/asset && cp -r test/level0/asset/* src/docker/asset/.

      - name: Build the docker-compose stack
        env:
          GITHUB_API_TOKEN: ${{ secrets.YAGNA_WORKFLOW_TOKEN }}
        run: docker-compose -f src/docker/docker-compose.yml up -d

      - name: Configure python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Print python and pip version
        run: python --version && pip --version

      - name: Install developer requirements
        run: pip install -r requirements.txt

      - name: Run setuptools
        run: python setup.py develop

      - name: Print installed package versions
        run: pip freeze

      - name: Sleep
        run: sleep 60

      - name: Check running containers
        run: docker ps

      - name: Run test suite
        run: python -m pytest test/level0 -svx --log-cli-level=DEBUG --assets-path test/level0/asset

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-logs
          path: /tmp/yagna-tests
