name: unit-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
    
      - name: Configure poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.6.1
          
      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run poe tests_unit
