name: unit-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
    
      - name: Configure poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.2
          
      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run poe unit_test
